// ============================================================
//  MEADOWS LANDSCAPES — TOOL FLEET DATA
//  Update this file whenever a tool is reassigned or added.
//  Then re-deploy to GitHub Pages (git add, commit, push).
// ============================================================

const TOOLS = [
  {
    id: "ML-001",
    description: "Cordless Drill/Driver 20V",
    brand: "DeWalt",
    model: "DCD791D2",
    serial: "SN-DW-001234",
    assetTag: "AT-001",
    assigned: "J. Smith",
    crew: "Crew A – ATL",
    storage: "Truck 12 / Job Box",
    status: "Active",
    purchaseDate: "2023-03-15",
    warrantyExp: "2026-03-15",
  },
  {
    id: "ML-002",
    description: "7-1/4\" Circular Saw 15A",
    brand: "Makita",
    model: "5007MGA",
    serial: "SN-MK-005521",
    assetTag: "AT-002",
    assigned: "D. Hernandez",
    crew: "Crew B – ATL",
    storage: "Truck 07 / Job Box",
    status: "Active",
    purchaseDate: "2022-08-01",
    warrantyExp: "2025-08-01",
  },
  {
    id: "ML-003",
    description: "60V Brushless String Trimmer",
    brand: "EGO",
    model: "ST1521S",
    serial: "SN-EG-009871",
    assetTag: "AT-003",
    assigned: "T. Williams",
    crew: "Crew C – ATL",
    storage: "Equipment Room – Bay 2",
    status: "Active",
    purchaseDate: "2024-01-05",
    warrantyExp: "2027-01-05",
  },
  {
    id: "ML-004",
    description: "76V Backpack Blower",
    brand: "EGO",
    model: "LB6003",
    serial: "SN-EG-010023",
    assetTag: "AT-004",
    assigned: "T. Williams",
    crew: "Crew C – ATL",
    storage: "Equipment Room – Bay 2",
    status: "Active",
    purchaseDate: "2024-01-05",
    warrantyExp: "2027-01-05",
  },
  {
    id: "ML-005",
    description: "1-1/8\" SDS+ Rotary Hammer",
    brand: "Milwaukee",
    model: "2712-20",
    serial: "SN-MW-221100",
    assetTag: "AT-005",
    assigned: "M. Davis",
    crew: "Crew D – Hardscape",
    storage: "Shop / Shelf B",
    status: "Active",
    purchaseDate: "2021-11-10",
    warrantyExp: "2024-11-10",
  },
  {
    id: "ML-006",
    description: "90cc Gas Plate Compactor",
    brand: "Multiquip",
    model: "MVC88SH4",
    serial: "SN-MQ-330041",
    assetTag: "AT-006",
    assigned: "R. Johnson",
    crew: "Crew E – Install",
    storage: "Trailer T-02",
    status: "Active",
    purchaseDate: "2020-05-20",
    warrantyExp: "2023-05-20",
  },
  {
    id: "ML-007",
    description: "4-1/2\" Angle Grinder 11A",
    brand: "DeWalt",
    model: "DWE402",
    serial: "SN-DW-440072",
    assetTag: "AT-007",
    assigned: "Unassigned",
    crew: "—",
    storage: "Shop / Shelf A",
    status: "Available",
    purchaseDate: "2022-07-14",
    warrantyExp: "2025-07-14",
  },
  {
    id: "ML-008",
    description: "Electric Wire Puller 18V",
    brand: "Greenlee",
    model: "CST155",
    serial: "SN-GL-552210",
    assetTag: "AT-008",
    assigned: "K. Martinez",
    crew: "Irrigation – ATL",
    storage: "Truck 15 / Irrigation Box",
    status: "Active",
    purchaseDate: "2023-09-01",
    warrantyExp: "2026-09-01",
  },
  {
    id: "ML-009",
    description: "14\" Gas Cut-Off Saw",
    brand: "Stihl",
    model: "TS420",
    serial: "SN-ST-678900",
    assetTag: "AT-009",
    assigned: "R. Johnson",
    crew: "Crew E – Install",
    storage: "Trailer T-02",
    status: "Active",
    purchaseDate: "2021-03-08",
    warrantyExp: "2024-03-08",
  },
  {
    id: "ML-010",
    description: "18V LXT Impact Driver",
    brand: "Makita",
    model: "XDT13Z",
    serial: "SN-MK-119955",
    assetTag: "AT-010",
    assigned: "J. Smith",
    crew: "Crew A – ATL",
    storage: "Truck 12 / Job Box",
    status: "Active",
    purchaseDate: "2023-05-17",
    warrantyExp: "2026-05-17",
  },
];
